version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - test
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Run build"
          command: yarn run build
      - run:
          name: "Run tests"
          command: yarn run test
      - run:
          name: "Run style check"
          command: yarn run check
